add_newline = true

[kubernetes]
disabled = true
format = 'on [☸ $context \($namespace\)]($style) '
style = 'cyan bold'

[package]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true

[azure]
disabled = true
